log_level: debug
host: ""
port: :8080
workdir: /tmp/godmod
name: travelite

postgres:
  user: postgres
  db_name: postgres
  password: admin
  host: postgres
  port: 5432

geography:
  srid: 4326

s3:
  bucket: trailite-1
  file_url: https://trailite-1.hb.bizmrg.com

cors:
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "HEAD"
  allow_credentials: true
  expose_headers:
  allow_headers:
    - "Origin"
    - "Content-Length"
    - "Content-Type"
#  allow_web_sockets: true
  allow_files: true
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:31888"
  max_age: 8760h

